<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('profileolabs_shoppingflux')->__('Shopping flux import orders') ?></h3></td><td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getImportOrdersUrl()?>')" type="button" class="scalable"><span><?php echo  Mage::helper('profileolabs_shoppingflux')->__('Shopping flux import new orders') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('profileolabs_shoppingflux')->__('Shopping flux import new orders')?>
        </td>
</table>